### ISSUE TITLE
Hey! Quick question about how you have your hotbed wired.

### ISSUE THREAD

**Issue by xontinuity** [DaniDiaz71/AnycubicChironUpgrade#2]
So I'm going to be doing this conversion for my Chiron but to an SKR v1.4. 

Basically, my Chiron has a MOSFET separate from the OG TriGorilla with a control wire to turn it on and off (this is for the hotbed).

Does your Chiron have this, and is the output from the hotbed terminal on the SKR you have pictured run to that control input? 

Thanks! 

PS: If you had stated this somewhere in the repository I missed it. If you did then sorry in advance for this redundant question... I just want to be certain I get everything set up properly!

**Comment by DaniDiaz71** [comment]
Hi,

Did you check all my pictures? I think there's a photo where you can see both mostef.

BR.
